### PR TITLE
Brief readme, and matrix add and inner product implementations

### PR DESCRIPTION
**Pull request by metasoarous**

### CODE REVIEW

**Comment by mikera** [comment]
Looks better.... can you pull and sync with my latest changes? Then I will merge. Thanks!

**Comment by metasoarous** [comment]
Sure thing.

**Comment by metasoarous** [comment]
OK; should be up to date.

**Comment by mikera** [comment]
Looks good - thanks! With the magic of open source I think will will have a fully working library in a day or so :-)

**Comment by metasoarous** [comment]
Unleash the open source elves!

**Pull request merged**
